spring:
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none #this is for avoiding second hibernate validation (no custom validator bean created, dependency repo = null)